### ISSUE TITLE
Investigate Xcode Cloud build

### ISSUE THREAD

**Issue by relja128** [mlcommons/mobile_app_open#121]
Can we use xcloud build for iOS CI?

**Comment by anhappdev** [comment]
XCode is currently in beta, invite only and free until the price is announced.
https://developer.apple.com/documentation/Xcode/Xcode-Cloud

Please comment your requirements to integrate XCode Cloud with our current CI/CD pipeline. I will collect, validate and update it here. I listed some requirements from my perspective.

## Requirements
### Must have:
- [x] Integration with TestFlight
- [x] Integration with GitHub
- [x] [Workflows](https://developer.apple.com/documentation/xcode/configuring-your-xcode-cloud-workflow-s-actions)
- [x] [Environment variables](https://developer.apple.com/documentation/xcode/environment-variable-reference)
- [x] [Custom build scripts](https://developer.apple.com/documentation/xcode/writing-custom-build-scripts)
- [x] Configuration via GUI
- [ ] Configuration via text file
- [x] Role and permission

### Should have:
- [x] [Webhooks](https://developer.apple.com/documentation/xcode/configuring-webhooks-in-xcode-cloud)

**Comment by d-uzlov** [comment]
>https://developer.apple.com/documentation/Xcode/Xcode-Cloud

>Note
Xcode Cloud is a feature of Xcode 13 and currently in beta

I remember we had issues building the Flutter app with XCode 13. Since, according to this note, XCode Cloud also uses XCode 13, we will probably encounter the same issues there.
Except maybe the issues we had were just bugs in XCode and/or Flutter that got fixed by now.

**Comment by freedomtan** [comment]
> > https://developer.apple.com/documentation/Xcode/Xcode-Cloud
> 
> > Note
> > Xcode Cloud is a feature of Xcode 13 and currently in beta
> 
> I remember we had issues building the Flutter app with XCode 13. Since, according to this note, XCode Cloud also uses XCode 13, we will probably encounter the same issues there. Except maybe the issues we had were just bugs in XCode and/or Flutter that got fixed by now.

What the issues are? I was able to built the app with Xcode 13, but it seems there are memory leaks. I didn't try find the cause.

**Comment by anhappdev** [comment]
> What the issues are? I was able to built the app with Xcode 13, but it seems there are memory leaks. I didn't try find the cause.

Yes, the app can be built successfully but will crash in run time (see https://github.com/mlcommons/mobile_app_flutter/issues/303)

**Comment by anhappdev** [comment]
Some other CI/CD services with macOS host:

**Pay per minute:**
* [GitHub Actions](https://docs.github.com/en/actions/using-github-hosted-runners/about-github-hosted-runners#supported-runners-and-hardware-resources)
* [CircleCI](https://circleci.com/build-environments/xcode/)
* [Azure Pipelines](https://docs.microsoft.com/en-us/azure/devops/pipelines/agents/hosted?view=azure-devops&tabs=yaml)

**Pay per month:**
* [Travis CI](https://docs.travis-ci.com/user/reference/osx/)
* [Macstadium](https://www.macstadium.com/)

**Comment by freedomtan** [comment]
FYR. I upgraded my macOS, iOS, and Xcode to 12.1, 15.2, and Xcode 13.2 yesterday. Then, I spent some time profiling and found that the culprit is [CoreML delegate's invoke function].(https://github.com/tensorflow/tensorflow/blob/master/tensorflow/lite/delegates/coreml/coreml_delegate_kernel.mm#L207-L230). Adding "@autoreleasepool {}" to it resolved the `EXC_RESOURCE` issue. Tested on iPhone 11 Pro and iPhone 13 running iOS 15.2. Supposedly, it worked for earlier Xcode 13.x and iOS.

**Comment by anhappdev** [comment]
@freedomtan Thanks for that info. I filled a bug report here https://github.com/tensorflow/tensorflow/issues/53461

**Comment by relja128** [comment]
Still no invite from Apple. Let's stay with Macincloud for now.

**Comment by anhappdev** [comment]
Closing this, until we receive an invitation from Apple or the service is public available.

**Comment by anhappdev** [comment]
XCode Cloud is now available.

**Comment by freedomtan** [comment]
let's check if we make xcode cloud work for our app.

**Comment by freedomtan** [comment]
Currently, it's limited to 25 hrs/month. But we cannot purchase more hours now. It's will be available later this summer.

**Comment by anhappdev** [comment]
Xcode Cloud subscription is now available.
https://developer.apple.com/news/?id=5hlzzu3u

**Comment by freedomtan** [comment]
@mkankana and @TheKanter please check if we (mlcommons) can pay for this and which account (XOR or mlcommons' account) to use. And which price tier?

**Comment by anhappdev** [comment]
We now have GitHub Actions for running iOS tests so the current 25 hours plan would be fine since we only use it for TestFlight deployment.
