### ISSUE TITLE
android-v2 issues tracking

### ISSUE THREAD

**Issue by freedomtan** [mlcommons/mobile_app_open#404]
Goal:
* a unified Android app which is performance parity with 2.0 submissions

performance parity with 2.0 submission
- [x] Google, checked by @kcwu 
- [x] MediaTek, checked by @freedomtan 
- [x] Qualcomm, checked by @mohitmundhragithub 
- [ ] Samsung,  waiting for https://github.com/mlcommons/mobile_app_open/pull/351?
 
some features:
- [x] configurable latency parameters

**Comment by freedomtan** [comment]
Let's wait for testing of #413 from @AhmedTElthakeb

**Comment by freedomtan** [comment]
@anhappdev please help creating a unified app based on current android-v2.

**Comment by anhappdev** [comment]
Here it is:
https://github.com/mlcommons/mobile_app_open/releases/tag/untagged-c84f27907ca965e5aa83

**Comment by freedomtan** [comment]
Dear colleagues, 
   Please help check if the unified app works as expected.

- [ ] Google Pixel backend
- [ ] MediaTek Neuron backend, checked by @freedomtan 
- [ ] Qualcomm SNPE backend
- [ ] Samsung Exynos backnd

**Comment by ptt2panda** [comment]
Verified that the unified app works as expected for Google, thanks.

**Comment by mohitmundhragithub** [comment]
verified that the app works as expected for Qualcomm. Thanks.

**Comment by freedomtan** [comment]
Many thanks for all. We can close this now :-)
