### ISSUE TITLE
issue tracking for 2.1 submission code freeze

### ISSUE THREAD

**Issue by freedomtan** [mlcommons/mobile_app_open#405]
Performance parity:
- [x] Samsung, need to resolve https://github.com/mlcommons/mobile_app_open/issues/379, to be confirmed this week
- [x] Qualcomm, looks good, @mohitmundhragithub 
- [x] MediaTeK, ~~if `shards_num` could be set 4 as shown in https://github.com/mlcommons/mobile_app_open/issues/402~~ good
- [x] Intel, not going to submit flutter this time. Let's skip checking for Intel for now.
- [x] Google, good, @kcwu, @ptt2panda 

features remained to be done:
- [x] https://github.com/mlcommons/mobile_app_open/issues/390
- [x] https://github.com/mlcommons/mobile_app_open/issues/389
- [x] https://github.com/mlcommons/mobile_app_open/issues/320
- [x] https://github.com/mlcommons/mobile_app_open/issues/373
- [x] https://github.com/mlcommons/mobile_app_open/issues/348
- [x] https://github.com/mlcommons/mobile_app_open/issues/324
- [x] ~~https://github.com/mlcommons/mobile_app_open/issues/241, what can we (non-qualcomm folks) help on this?~~
- [x] https://github.com/mlcommons/mobile_app_open/issues/307
- [x] https://github.com/mlcommons/mobile_app_open/pull/425

**Comment by freedomtan** [comment]
Let's wait for the closing of #379, then we can branch out a v2.1 for 2.1 submission.

**Comment by freedomtan** [comment]
Supposedly, we can create a branch from commits after dec8b434fb0 or efe21c2.

Let's check https://github.com/mlcommons/mobile_app_open/commits/master

**Comment by freedomtan** [comment]
@mohitmundhragithub to merge #425, then @anhappdev or @d-uzlov can help create a 2.1 submission branch.

**Comment by freedomtan** [comment]
@mkankana and @willc2010 v2.1 submission branch created
