### ISSUE TITLE
Add result upload and download feature

### ISSUE THREAD

**Issue by anhappdev** [mlcommons/mobile_app_open#670]
- [X] The app can upload result files to a cloud storage (#703)
- [X] The app can download result files from a cloud storage (only results from the same user_id) (#752)
- [x] Provide option to convert from an anonymous account to a normal account (#757)

Background:
In the past, we tried to use the Firebase Database for storing results but it has very limited capabilities in filtering (see https://github.com/mlcommons/mobile_app_open/issues/490). Since we don't expect the data (the result) to be modified, and the amount of data will not be big, we will be fine with just storing the result as a `json/text` file, then upload it to a cloud storage, and download other results from the cloud storage and do all the filtering locally on-device. The filtering is already implemented in https://github.com/mlcommons/mobile_app_open/issues/641.
