### ISSUE TITLE
Implement Stable Diffusion for mobile_back_apple

### ISSUE THREAD

**Issue by anhappdev** [mlcommons/mobile_app_open#919]

**Comment by RSMNYS** [comment]
### TODO List

- [ ] **Implement Stable Diffusion for CoreML** (from the existing TF implementation). Add implementation in Swift, by utilising CoreML API. 
- [ ] **Convert TF lite models (text_encoder, stable_diffusion_model, decoder) to mlPackage**
- [ ] **Implement stable diffusion pipeline**

@freedomtan

**Comment by freedomtan** [comment]
FYR. Apple already implemented Stable Diffusion in Swift. Please check if we can reuse Apple's implementation first.
https://github.com/apple/ml-stable-diffusion
